@extends('adminlte::page')

@section('title', 'Medical Assistant')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>
    <p>You are logged in!</p>

@stop